Improvement Pack 12.2024
Added generator hooks
New posts-arch module
New posts-rss module
New template-simpleblog
pages, posts, posts-tags and minify modules: added parallel rendering options
posts and posts-tags modules: ability to add code at the beginning and end of the document
posts and posts-tags modules: ability to disable list generation
posts and posts-tags modules: fixed html headers leak bug from post metadata in post lists
posts, posts-tags and templates modules: added post id option
posts module: added copy file function for posts
posts and templates modules: added integration with posts-tags module
Improved templates module
Improved gzip module
Improved template-default
Lighter template-default-nojs style

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -1,6 +1,6 @@
 #!/usr/bin/env sh
 # Bash Static Site Generator - entry point
-# 2021 MissKittin@GitHub
+# 2021 2024 MissKittin@GitHub
 # Required tools for entrypoint: date dirname readlink tr sort cat mv rm
 
 echo ' :: Checking required tools'
@@ -14,12 +14,12 @@ for tool in 'dirname' 'readlink'; do
 		exit 1
 	fi
 done
-unset tool
 
 # global variables (you can rewrite in database/defaults.rc.d)
 	export SSG__root="$(dirname "$(readlink -f "${0}")")"
 	export SSG__modules="${SSG__root}/modules"
 	export SSG__database="${SSG__root}/database"
+	export SSG__user_modules="${SSG__database}/modules"
 	export SSG__generated="${SSG__root}/generated"
 	export SSG__lib="${SSG__root}/lib"
 	[ -d "${SSG__root}/bin" ] && export PATH="${SSG__root}/bin:${PATH}"
@@ -47,8 +47,9 @@ unset tool
 		echo ' :: Checking required tools'
 		moduleRequiredTools='date tr sort cat mv rm' # for entrypoint
 
-		for module in ${SSG__modules}/*; do
-			[ "${module}" = "${SSG__modules}/*" ] && break
+		for module in ${SSG__modules}/* ${SSG__user_modules}/*; do
+			[ "${module}" = "${SSG__modules}/*" ] && continue
+			[ "${module}" = "${SSG__user_modules}/*" ] && break
 			[ -e "${module}/command-stack" ] && check_disabled_modules "${module##*/}" "${defaults__disabled_modules}" && moduleRequiredTools="${moduleRequiredTools} $(cat "${module}/command-stack")"
 		done
 
@@ -65,21 +66,21 @@ unset tool
 					echo -n 'Continue anyway? (y/[N]) '
 					read answer
 					[ ! "${answer}" = 'y' ] && exit 1
-					unset answer
+					unset 'answer'
 					break
 				fi
 			done
 		fi
 
-		unset moduleRequiredTools
-		unset tool
+		unset 'moduleRequiredTools'
+		unset 'tool'
 	fi
 
 # module dependencies check
 	if "${entrypointCheckModules}"; then
 		echo ' :: Checking modules dependencies'
-		for module in ${SSG__modules}/*; do
-			[ "${module}" = "${SSG__modules}/*" ] && break
+		for module in ${SSG__modules}/* ${SSG__user_modules}/*; do
+			[ "${module}" = "${SSG__modules}/*" ] && continue
 			if [ -e "${module}/dependencies" ] && check_disabled_modules "${module##*/}" "${defaults__disabled_modules}"; then
 				echo -n "Checking module ${module##*/}"
 				if ! \
@@ -94,7 +95,7 @@ unset tool
 					echo -n 'Continue anyway? (y/[N]) '
 					read answer
 					[ ! "${answer}" = 'y' ] && exit 1
-					unset answer
+					unset 'answer'
 					break
 				else
 					echo ' [ OK ]'
@@ -103,26 +104,33 @@ unset tool
 		done
 	fi
 
+if [ -e "${SSG__database}/generate-hooks/pre-generate.rc" ]; then
+	echo ' :: Starting pre-generate hook'
+	. "${SSG__database}/generate-hooks/pre-generate.rc"
+fi
+
 # output directory
-	if [ -e "${SSG__generated}" ]; then
-		if "${defaults__archive_old_generated}"; then
-			echo ' :: Archiving previously generated files'
-			mv "${SSG__generated}" "${SSG__generated}-$(date '+%Y%m%d%H%M%S')"
-		else
-			echo ' :: Removing previously generated files'
-			rm -r ${SSG__generated}/* > /dev/null 2>&1
-		fi
+	[ -e "${SSG__generated}" ] && if "${defaults__archive_old_generated}"; then
+		echo ' :: Archiving previously generated files'
+		mv "${SSG__generated}" "${SSG__generated}-$(date '+%Y%m%d%H%M%S')"
+	else
+		echo ' :: Removing previously generated files'
+		rm -r ${SSG__generated}/* > /dev/null 2>&1
 	fi
 
 # modules generators
-	for module in ${SSG__modules}/*; do
-		[ "${module}" = "${SSG__root}/modules/*" ] && echo "No modules installed"
+	for module in ${SSG__modules}/* ${SSG__user_modules}/*; do
+		[ "${module}" = "${SSG__modules}/*" ] && echo 'No modules installed'
 		if [ -x "${module}/generate" ]; then
 			moduleName="${module##*/}"
 			if check_disabled_modules "${moduleName}" "${defaults__disabled_modules}"; then
 				echo " :: Running ${moduleName} module"
 				"${module}/generate"
-				echo " :: ${moduleName} module ended"
+				if [ "$?" = '0' ]; then
+					echo " :: ${moduleName} module ended"
+				else
+					echo " :: ${moduleName} module failed"
+				fi
 
 				if [ -e "${SSG__generated}/.reimport-defaults" ]; then
 					echo ' :: Re-importing defaults variables'
@@ -135,13 +143,22 @@ unset tool
 		fi
 	done
 
+if [ -e "${SSG__database}/generate-hooks/post-generate.rc" ]; then
+	echo ' :: Starting post-generate hook'
+	. "${SSG__database}/generate-hooks/post-generate.rc"
+fi
+
 # default module check
-	if [ "${defaults__home_module}" = '' ] || [ ! -e "${SSG__modules}/${defaults__home_module}" ]; then
+	if [ "${defaults__home_module}" = '' ]; then
+		echo "error: default module '${defaults__home_module}' is not defined"
+		exit 1
+	fi
+	if [ ! -e "${SSG__modules}/${defaults__home_module}" ] && [ ! -e "${SSG__user_modules}/${defaults__home_module}" ]; then
 		echo "error: default module '${defaults__home_module}' not found in modules"
 		exit 1
 	fi
 
 # execution time measurement (2)
-	echo " :: Script executed in $(($(date '+%s')-entrypointStartTime)) seconds"
+	[ ! "${entrypointStartTime}" = '' ] && echo " :: Script executed in $(($(date '+%s')-entrypointStartTime)) seconds"
 
 exit 0
diff --git a/modules/pages/generate b/modules/pages/generate
--- a/modules/pages/generate
+++ b/modules/pages/generate
@@ -1,7 +1,9 @@
 #!/usr/bin/env sh
 # Pages generator module
+__module_name__='pages'
 
 # defaults variables
+	pages__dbdir='pages'
 	. "${0%/*}/defaults.rc.d/pages.rc"
 
 # variables'
@@ -9,8 +11,8 @@
 	. "${SSG__lib}/import-defaults.rc"
 
 # directory in database
-	if [ ! -e "${SSG__database}/pages" ]; then
-		echo '"pages" directory not found in database'
+	if [ ! -e "${SSG__database}/${pages__dbdir}" ]; then
+		echo '"'"${pages__dbdir}"'" directory not found in database'
 		exit 1
 	fi
 
@@ -18,8 +20,9 @@
 	pages__render_script()
 	{
 		local script="${entrypoint%/*}/${1}"
-		local scriptPath="$(echo -n "${script}" | sed 's|'"${SSG__database}/pages/"'||g')"
-		local renderedScriptPath="${SSG__generated}/${pages__generated_directory}${scriptPath%/*}"
+		local scriptPath="$(echo -n "${script}" | sed 's|'"${SSG__database}/${pages__dbdir}/"'||g')"
+		local renderedScriptPathSubpath="${3}"; [ ! "${renderedScriptPathSubpath}" = '' ] && renderedScriptPathSubpath="/${renderedScriptPathSubpath}"
+		local renderedScriptPath="${SSG__generated}/${pages__generated_directory}${scriptPath%/*}${renderedScriptPathSubpath}"
 
 		[ -e "${renderedScriptPath}" ] && echo "error: directory conflict on ${pages__generated_directory}${scriptPath%/*}"
 
@@ -29,40 +32,55 @@
 	}
 	pages__copy_file()
 	{
-		local scriptLocation="${entrypoint%/*}/${1}"
-		scriptLocation="${scriptLocation%/*}"
+		local scriptLocation="${entrypoint%/*}"
 
-		local renderedFilePath="${renderedScriptPath}/${1}"
-		renderedFilePath="${renderedFilePath%/*}"
+		if [ "${renderedScriptPath}" = '' ]; then
+			local scriptPath="$(echo -n "${entrypoint%/*}" | sed 's|'"${SSG__database}/${pages__dbdir}/"'||g')"
+			local renderedScriptPath="${SSG__generated}/${pages__generated_directory}${scriptPath%/*}"
+		fi
 
 		if [ -e "${scriptLocation}/${1}" ]; then
-			echo " Copying file ${1}" >&2
+			if [ -f "${scriptLocation}/${1}" ]; then
+				echo " Copying file '${1}' to '${2}'" >&2
+			elif [ -d "${scriptLocation}/${1}" ]; then
+				echo " Copying directory '${1}' to '${2}'" >&2
+			else
+				echo " Copying '${1}' to '${2}'" >&2
+			fi
 
-			[ ! -e "${renderedFilePath}" ] && mkdir "${renderedFilePath}"
-			cp "${scriptLocation}/${1}" "${renderedScriptPath}/${1}"
+			[ ! -e "${renderedScriptPath}" ] && mkdir "${renderedScriptPath}"
+			cp -r "${scriptLocation}/${1}" "${renderedScriptPath}/${2}"
 		else
-			echo " File ${1} not exists" >&2
+			echo "  File ${scriptLocation}/${1} not exists" >&2
 		fi
 	}
 
 # database processing
-	for page in ${SSG__database}/pages/*; do
-		[ "${page}" = "${SSG__database}/pages/*" ] && break
+	for page in ${SSG__database}/${pages__dbdir}/*; do
+		[ "${page}" = "${SSG__database}/${pages__dbdir}/*" ] && break
 
 		if [ -d "${page}" ]; then
 			echo "Generating page '${page##*/}'"
-			find "${page}" -name 'entrypoint.rc' | while read entrypoint; do
-				unset page
-				. "${entrypoint}"
-			done
+			if "${pages__parallel_rendering}"; then
+				find "${page}" -name 'entrypoint.rc' | while read entrypoint; do
+					unset 'page'
+					. "${entrypoint}"
+				done &
+			else
+				find "${page}" -name 'entrypoint.rc' | while read entrypoint; do
+					unset 'page'
+					. "${entrypoint}"
+				done
+			fi
 		fi
 	done
+	"${pages__parallel_rendering}" && wait
 
 # home page processing
 	. "${SSG__lib}/import-includes.rc"
-	if [ "${pages__default_page}" = '' ]; then
+	[ "${defaults__home_module}" = "${__module_name__}" ] && if [ "${pages__default_page}" = '' ]; then
 		echo 'pages__default_page is empty - home page not copied'
-	elif [ "${defaults__home_module}" = 'pages' ]; then
+	else
 		echo "This is default module - moving '${pages__default_page}' page"
 
 		if [ -e "${SSG__generated}/${pages__generated_directory}${pages__default_page}/${defaults__default_file_name}${defaults__default_file_extension}" ]; then
diff --git a/modules/posts-tags/generate b/modules/posts-tags/generate
--- a/modules/posts-tags/generate
+++ b/modules/posts-tags/generate
@@ -1,7 +1,9 @@
 #!/usr/bin/env sh
-# post-tags generator module
+# Tag list generator module
+__module_name__='posts-tags'
 
 # defaults variables
+	posts__dbdir='posts'
 	. "${SSG__modules}/posts/defaults.rc.d/posts.rc"
 	. "${0%/*}/defaults.rc.d/posts-tags.rc"
 
@@ -12,8 +14,8 @@
 	[ "${posts_tags__generated_directory}" = '' ] && posts_tags__generated_directory='tag'
 
 # directory in database
-	if [ ! -e "${SSG__database}/posts" ]; then
-		echo '"posts" directory not found in database'
+	if [ ! -e "${SSG__database}/${posts__dbdir}" ]; then
+		echo '"'"${posts__dbdir}"'" directory not found in database'
 		exit 1
 	fi
 
@@ -22,9 +24,9 @@
 	{
 		if [ ! "${1}" = 'noTitleLink' ]; then  # for post metadata
 			. "${post}/meta.rc"
-			template_no_title_link='false'
+			template__no_title_link='false'
 		else
-			template_no_title_link='true'
+			template__no_title_link='true'
 		fi
 
 		if [ -e "${post}/tags" ]; then
@@ -35,20 +37,24 @@
 				posts__post_tags="${posts__post_tags} #${tag##*/}"
 			done
 			posts__post_tags="${posts__post_tags#?}"
-			unset tag
+			unset 'tag'
 		fi
 
-		if ! template__get_part "${defaults__template}" 'resource' 'posts-content'; then
-			echo "error: template ${defaults__template} does not provide posts-content.rc" >&2
+		if ! templates__current_get_part 'resource' 'posts-content'; then
+			echo "error: template ${templates__template} does not provide posts-content.rc" >&2
 		fi
 
-		unset posts__post_title; unset posts__post_date; unset posts__post_tags
-		unset template_no_title_link
+		unset 'posts__post_title'
+		unset 'posts__post_date'
+		unset 'posts__post_id'
+		unset 'posts__post_tags'
+
+		unset 'template__no_title_link'
 	}
 
 # database processing - read all tags
-	for post in ${SSG__database}/posts/public_*; do
-		[ "${post}" = "${SSG__database}/posts/public_*" ] && break
+	for post in ${SSG__database}/${posts__dbdir}/public_*; do
+		[ "${post}" = "${SSG__database}/${posts__dbdir}/public_*" ] && break
 		for tag in ${post}/tags/*; do
 			[ "${tag}" = "${post}/tags/*" ] && break
 			posts__tag_list="${posts__tag_list} ${tag##*/}"
@@ -57,15 +63,30 @@
 	[ ! "${posts__tag_list}" = '' ] && posts__tag_list="$(echo -n "${posts__tag_list}" | tr ' ' '\n' | sort -u)" # sort tag list
 
 # tag list processing
+	posts_tags__generate_tag_list()
+	{
+		local template__html_headers="${posts_tags__list_html_headers}"
+		posts_tags__html_title
+		echo -n "${posts_tags__list_header_content}"
+		templates__current_get_part 'top'
+
+		if ! templates__current_get_part 'resource' 'tags-list'; then
+			echo "error: template ${templates__template} does not provide tags-list.rc" >&2
+		fi
+
+		templates__current_get_part 'bottom'
+		echo -n "${posts_tags__list_footer_content}"
+	}
 	[ ! -e "${SSG__generated}/${posts_tags__generated_directory}" ] && mkdir -p "${SSG__generated}/${posts_tags__generated_directory}"
-
-	template__get_part "${defaults__template}" 'top' >> "${SSG__generated}/${posts_tags__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}"
-
-	if ! template__get_part "${defaults__template}" 'resource' 'tags-list' >> "${SSG__generated}/${posts_tags__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}"; then
-		echo "error: template ${defaults__template} does not provide tags-list.rc"
+	if "${posts_tags__enable_tag_lists}"; then
+		if "${posts_tags__parallel_rendering}"; then
+			posts_tags__generate_tag_list >> "${SSG__generated}/${posts_tags__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}" &
+		else
+			posts_tags__generate_tag_list >> "${SSG__generated}/${posts_tags__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}"
+		fi
+	else
+		echo 'Tag list generation is disabled'
 	fi
-
-	template__get_part "${defaults__template}" 'bottom' >> "${SSG__generated}/${posts_tags__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}"
 
 # tag listings processing
 	if [ ! "${posts__tag_list}" = '' ]; then
@@ -74,34 +95,38 @@
 			echo " Processing page ${1}"
 
 			local post
-			local renderedPageDir="${SSG__generated}/${posts_tags__generated_directory}/${tag}/${1}" # cache
 			local currentPageNumber="${1}" # for template
-			local template__html_title="${posts_tags__list_html_title}"
+			local template__html_headers="${posts_tags__listing_html_headers}"
+			local template__html_title; posts_tags__list_html_title
+
+			# cache
+			if [ "${currentPageNumber}" = '1' ]; then
+				local renderedPageDir="${SSG__generated}/${posts_tags__generated_directory}/${tag}"
+			else
+				local renderedPageDir="${SSG__generated}/${posts_tags__generated_directory}/${tag}/${1}"
+			fi
 
 			[ ! -e "${renderedPageDir}" ] && mkdir -p "${renderedPageDir}"
 
-			template__get_part "${defaults__template}" 'top' >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			echo -n "${posts_tags__listing_header_content}" >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			templates__current_get_part 'top' >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
 
 			for post in ${2}; do
 				postName="${post##*/}"
 				echo "  Adding post ${postName##*_}"
-				unset postName
+				unset 'postName'
 
 				local renderedPost="${post##*_}"
 				generatePostBox >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-				unset renderedPost
+				unset 'renderedPost'
 			done
 
-			if ! template__get_part "${defaults__template}" 'resource' 'tags-pages' >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"; then
-				echo "error: template ${defaults__template} does not provide tags-pages.rc"
+			if ! templates__current_get_part 'resource' 'tags-pages' >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"; then
+				echo "error: template ${templates__template} does not provide tags-pages.rc"
 			fi
 
-			template__get_part "${defaults__template}" 'bottom' >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-
-			unset template__html_title
-			unset currentPageNumber
-			unset renderedPageDir
-			unset post
+			templates__current_get_part 'bottom' >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			echo -n "${posts_tags__listing_footer_content}" >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
 		}
 
 		for tag in ${posts__tag_list}; do
@@ -112,19 +137,30 @@
 			posts_tags__current_page_indicator='1'
 
 			posts_tags__counted_posts='0'
-			for post in $(find ${SSG__database}/posts/public_* -type f | grep '/tags/' | grep "${tag}"); do
+			posts_tags__counted_posts_find="$(find ${SSG__database}/${posts__dbdir}/public_* -type f -path "*/tags/${tag}")" # cache
+			for post in ${posts_tags__counted_posts_find}; do
 				posts_tags__counted_posts="$((posts_tags__counted_posts+1))"
 			done
-			posts_tags__counted_pages="$(echo "${posts_tags__counted_posts} ${posts__posts_per_page}" | awk '{print ($1/$2)+0.9}' | awk '{printf "%.0d", $1}')"
-			unset post
-			unset posts_tags__counted_posts
+			posts_tags__counted_pages="$(awk '
+				BEGIN {
+					printf \
+						"%.0d", \
+						('"${posts_tags__counted_posts}"'/'"${posts__posts_per_page}"')+0.9 \
+				}
+			')"
+			unset 'post'
+			unset 'posts_tags__counted_posts'
 
-			for post in $(find ${SSG__database}/posts/public_* -type f | grep '/tags/' | grep "${tag}" | tac); do
+			for post in $(echo "${posts_tags__counted_posts_find}" | tac); do
 				post="$(echo -n "${post}" | sed 's|/tags/'"${tag}"'||g')"
 				posts_tags__list="${posts_tags__list} ${post}"
 
 				if [ "${posts_tags__list_limit_indicator}" = "${posts__posts_per_page}" ]; then
-					posts_tags__generate_list "${posts_tags__current_page_indicator}" "${posts_tags__list}"
+					if "${posts_tags__parallel_rendering}"; then
+						posts_tags__generate_list "${posts_tags__current_page_indicator}" "${posts_tags__list}" &
+					else
+						posts_tags__generate_list "${posts_tags__current_page_indicator}" "${posts_tags__list}"
+					fi
 
 					posts_tags__list=''
 					posts_tags__list_limit_indicator='1'
@@ -133,26 +169,31 @@
 					posts_tags__list_limit_indicator="$((posts_tags__list_limit_indicator+1))"
 				fi
 			done
-			[ ! "${posts_tags__list}" = '' ] && posts_tags__generate_list "${posts_tags__current_page_indicator}" "${posts_tags__list}"
+			[ ! "${posts_tags__list}" = '' ] && if "${posts_tags__parallel_rendering}"; then
+				posts_tags__generate_list "${posts_tags__current_page_indicator}" "${posts_tags__list}" &
+			else
+				posts_tags__generate_list "${posts_tags__current_page_indicator}" "${posts_tags__list}"
+			fi
 
-			mv "${SSG__generated}/${posts_tags__generated_directory}/${tag}/1/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${posts_tags__generated_directory}/${tag}/${defaults__default_file_name}${defaults__default_file_extension}"
-			rmdir "${SSG__generated}/${posts_tags__generated_directory}/${tag}/1"
-
-			unset post
-			unset posts_tags__counted_pages
-			unset posts_tags__current_page_indicator
-			unset posts_tags__list_limit_indicator
-			unset posts_tags__list
+			unset 'post'
+			unset 'posts_tags__counted_pages'
+			unset 'posts_tags__current_page_indicator'
+			unset 'posts_tags__list_limit_indicator'
+			unset 'posts_tags__list'
 		done
 
-		unset posts_tags__generate_list
-		unset tag
+		"${posts_tags__parallel_rendering}" && wait
+
+		unset 'posts_tags__generate_list'
+		unset 'tag'
 	fi
 
 # home page processing
-	if [ "${defaults__home_module}" = 'posts-tags' ]; then
-			echo "This is default module - generating home page"
-			mv "${SSG__generated}/${posts_tags__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
+	[ "${defaults__home_module}" = "${__module_name__}" ] && if "${posts_tags__enable_tag_lists}"; then
+		echo 'This is default module - generating home page'
+		mv "${SSG__generated}/${posts_tags__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
+	else
+		'Error: posts_tags__enable_tag_lists is false - this module cannot be the default module'
 	fi
 
 exit 0
diff --git a/modules/posts/generate b/modules/posts/generate
--- a/modules/posts/generate
+++ b/modules/posts/generate
@@ -1,7 +1,9 @@
 #!/usr/bin/env sh
-# post generator module
+# Post generator module
+__module_name__='posts'
 
 # defaults variables
+	posts__dbdir='posts'
 	. "${0%/*}/defaults.rc.d/posts.rc"
 
 # variables
@@ -10,19 +12,35 @@
 	. "${SSG__lib}/import-defaults.rc"
 
 # directory in database
-	if [ ! -e "${SSG__database}/posts" ]; then
-		echo '"posts" directory not found in database'
+	if [ ! -e "${SSG__database}/${posts__dbdir}" ]; then
+		echo '"'"${posts__dbdir}"'" directory not found in database'
 		exit 1
 	fi
 
 # functions
+	posts__copy_file()
+	{
+		[ ! -e "${renderedPostDir}/${2}" ] && if [ -e "${post}/${1}" ]; then
+			if [ -f "${post}/${1}" ]; then
+				echo " Copying file '${1}' to '${2}'" >&2
+			elif [ -d "${post}/${1}" ]; then
+				echo " Copying directory '${1}' to '${2}'" >&2
+			else
+				echo " Copying '${1}' to '${2}'" >&2
+			fi
+
+			cp -r "${post}/${1}" "${renderedPostDir}/${2}"
+		else
+			echo "  File ${post}/${1} not exists" >&2
+		fi
+	}
 	generatePostBox()
 	{
 		if [ ! "${1}" = 'noTitleLink' ]; then  # for post metadata
 			. "${post}/meta.rc"
-			template_no_title_link='false'
+			template__no_title_link='false'
 		else
-			template_no_title_link='true'
+			template__no_title_link='true'
 		fi
 
 		if [ -e "${post}/tags" ]; then
@@ -33,159 +51,206 @@
 				posts__post_tags="${posts__post_tags} #${tag##*/}"
 			done
 			posts__post_tags="${posts__post_tags#?}"
-			unset tag
+			unset 'tag'
 		fi
 
-		if ! template__get_part "${defaults__template}" 'resource' 'posts-content'; then
-			echo "error: template ${defaults__template} does not provide posts-content.rc" >&2
+		if ! templates__current_get_part 'resource' 'posts-content'; then
+			echo "error: template ${templates__template} does not provide posts-content.rc" >&2
 		fi
 
-		unset posts__post_title; unset posts__post_date; unset posts__post_tags
-		unset template_no_title_link
+		unset 'posts__post_title'
+		unset 'posts__post_date'
+		unset 'posts__post_id'
+		unset 'posts__post_tags'
+
+		unset 'template__no_title_link'
 	}
 
 # database preprocessing - count pages
 	posts__counted_posts='1'
-	for post in ${SSG__database}/posts/public_*; do
-		[ "${post}" = "${SSG__database}/posts/public_*" ] && break
+	for post in ${SSG__database}/${posts__dbdir}/public_*; do
+		[ "${post}" = "${SSG__database}/${posts__dbdir}/public_*" ] && break
 		posts__counted_posts="$((posts__counted_posts+1))"
 	done
 
-	posts__counted_pages="$(echo "${posts__counted_posts} ${posts__posts_per_page}" | awk '{print ($1/$2)+0.9}' | awk '{printf "%.0d", $1}')"
+	posts__counted_pages="$(awk '
+		BEGIN {
+			printf \
+				"%.0d", \
+				('"${posts__counted_posts}"'/'"${posts__posts_per_page}"')+0.9 \
+		}
+	')"
 
-	unset post
-	unset posts__counted_posts
+	unset 'post'
+	unset 'posts__counted_posts'
 
 # database processing
-	for post in ${SSG__database}/posts/public_*; do
-		if [ "${post}" = "${SSG__database}/posts/public_*" ]; then
+	generateForPost()
+	{
+		postName="${post##*/}"
+		echo "Generating ${1} post ${postName##*_}"
+		unset 'postName'
+
+		renderedPostDir="${post##*/}"; renderedPostDir="${renderedPostDir##*_}"; renderedPostDir="${SSG__generated}/${posts__generated_post_directory}${renderedPostDir}" # cache
+		[ ! -e "${renderedPostDir}" ] && mkdir -p "${renderedPostDir}"
+
+		. "${post}/meta.rc" # for template settings
+		posts__post_html_title
+
+		echo -n "${posts__post_header_content}" >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		templates__current_get_part 'top' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		generatePostBox 'noTitleLink' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		templates__current_get_part 'bottom' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		echo -n "${posts__post_footer_content}" >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+	}
+
+	for post in ${SSG__database}/${posts__dbdir}/public_*; do
+		if [ "${post}" = "${SSG__database}/${posts__dbdir}/public_*" ]; then
 			echo 'No published posts found in database'
 			break
 		fi
 
-		postName="${post##*/}"
-		echo "Generating published post ${postName##*_}"
-		unset postName
-
-		renderedPostDir="${post##*/}"; renderedPostDir="${renderedPostDir##*_}"; renderedPostDir="${SSG__generated}/${posts__generated_post_directory}${renderedPostDir}" # cache
-		[ ! -e "${renderedPostDir}" ] && mkdir -p "${renderedPostDir}"
-
-		. "${post}/meta.rc" # for template settings
-		[ ! "${posts__post_title}" = '' ] && template__html_title="${posts__post_title}" # set html title
-
-		template__get_part "${defaults__template}" 'top' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-		generatePostBox 'noTitleLink' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-		template__get_part "${defaults__template}" 'bottom' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		if "${posts__parallel_rendering}"; then
+			generateForPost 'published' &
+		else
+			generateForPost 'published'
+		fi
 	done
-	for post in ${SSG__database}/posts/hidden_*; do
-		if [ "${post}" = "${SSG__database}/posts/hidden_*" ]; then
+	for post in ${SSG__database}/${posts__dbdir}/hidden_*; do
+		if [ "${post}" = "${SSG__database}/${posts__dbdir}/hidden_*" ]; then
 			echo 'No hidden posts found in database'
 			break
 		fi
 
-		postName="${post##*/}"
-		echo "Generating hidden post ${postName##*_}"
-		unset postName
-
-		renderedPostDir="${post##*/}"; renderedPostDir="${renderedPostDir##*_}"; renderedPostDir="${SSG__generated}/${posts__generated_post_directory}${renderedPostDir}" # cache
-		[ ! -e "${renderedPostDir}" ] && mkdir -p "${renderedPostDir}"
-
-		. "${post}/meta.rc" # for template settings
-		[ ! "${posts__post_title}" = '' ] && template__html_title="${posts__post_title}" # set html title
-
-		template__get_part "${defaults__template}" 'top' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-		generatePostBox 'noTitleLink' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-		template__get_part "${defaults__template}" 'bottom' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		if "${posts__parallel_rendering}"; then
+			generateForPost 'hidden' &
+		else
+			generateForPost 'hidden'
+		fi
 	done
 
-# posts list processing
-	posts__generate_list()
+	unset 'generateForPost'
+
+# the files were already copied
+	posts__copy_file()
 	{
-		local post
-		local currentPageNumber="${1}" # for template
-		local renderedPostDir="${SSG__generated}/${posts__generated_page_directory}${currentPageNumber}" # cache
-		local template__html_title="${posts__list_html_title}"
-
-		echo "Processing page ${currentPageNumber}"
-
-		"${posts__no_first_page_mode}" && [ "${currentPageNumber}" = '1' ] && \
-			renderedPostDir="${SSG__generated}/${posts__generated_page_directory}"
-
-		[ ! -e "${renderedPostDir}" ] && mkdir -p "${renderedPostDir}"
-
-		template__get_part "${defaults__template}" 'top' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-
-		for post in ${2}; do
-			echo " Adding post ${post##*/}"
-
-			local renderedPost="${post##*_}"
-			generatePostBox >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-			unset renderedPost
-		done
-
-		if ! template__get_part "${defaults__template}" 'resource' 'posts-pages' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"; then
-			echo "error: template ${defaults__template} does not provide posts-pages.rc"
-		fi
-
-		template__get_part "${defaults__template}" 'bottom' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		true
 	}
 
-	# reverse order
-	posts__post_pivot=''
-	for post in ${SSG__database}/posts/public_*; do
-		posts__post_pivot="${post} ${posts__post_pivot}"
-	done
-	post="${posts__post_pivot}"
-	unset posts__post_pivot
+# posts list processing
+	if "${posts__enable_post_lists}"; then
+		posts__generate_list()
+		{
+			local post
+			local currentPageNumber="${1}" # for template
+			local renderedPostDir="${SSG__generated}/${posts__generated_page_directory}${currentPageNumber}" # cache
+			local template__html_headers="${posts__list_html_headers}"
+			local template__html_title; posts__list_html_title
 
-	posts__list=''
-	posts__list_limit_indicator='1'
-	posts__current_page_indicator='1'
+			echo "Processing page ${currentPageNumber}"
 
-	for post in ${post}; do
-		if [ "${post}" = "${SSG__database}/posts/public_*" ]; then
+			"${posts__no_first_page_mode}" && [ "${currentPageNumber}" = '1' ] && \
+				renderedPostDir="${SSG__generated}/${posts__generated_page_directory}"
 
-			mkdir -p "${SSG__generated}/${posts__generated_page_directory}1"
-			template__get_part "${defaults__template}" 'top' >> "${SSG__generated}/${posts__generated_page_directory}1/${defaults__default_file_name}${defaults__default_file_extension}"
-			echo "${posts__label_not_found}" >> "${SSG__generated}/${posts__generated_page_directory}1/${defaults__default_file_name}${defaults__default_file_extension}"
-			template__get_part "${defaults__template}" 'bottom' >> "${SSG__generated}/${posts__generated_page_directory}1/${defaults__default_file_name}${defaults__default_file_extension}"
+			[ ! -e "${renderedPostDir}" ] && mkdir -p "${renderedPostDir}"
 
-			break
-		fi
+			echo -n "${posts__list_header_content}" >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			templates__current_get_part 'top' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
 
-		posts__list="${posts__list} ${post}"
-		if [ "${posts__list_limit_indicator}" = "${posts__posts_per_page}" ]; then
-			posts__generate_list "${posts__current_page_indicator}" "${posts__list}"
+			for post in ${2}; do
+				echo " Adding post ${post##*/}"
 
-			posts__list=''
-			posts__list_limit_indicator='1'
-			posts__current_page_indicator="$((posts__current_page_indicator+1))"
+				local renderedPost="${post##*_}"
+				generatePostBox >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+				unset 'renderedPost'
+			done
+
+			if ! templates__current_get_part 'resource' 'posts-pages' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"; then
+				echo "error: template ${templates__template} does not provide posts-pages.rc"
+			fi
+
+			templates__current_get_part 'bottom' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			echo -n "${posts__list_footer_content}" >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		}
+
+		# reverse order
+		posts__post_pivot=''
+		for post in ${SSG__database}/${posts__dbdir}/public_*; do
+			posts__post_pivot="${post} ${posts__post_pivot}"
+		done
+		post="${posts__post_pivot}"
+		unset 'posts__post_pivot'
+
+		posts__list=''
+		posts__list_limit_indicator='1'
+		posts__current_page_indicator='1'
+
+		for post in ${post}; do
+			if [ "${post}" = "${SSG__database}/${posts__dbdir}/public_*" ]; then
+				posts__no_posts_found_path='1'
+				"${posts__no_first_page_mode}" && posts__no_posts_found_path=''
+
+				mkdir -p "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}"
+				echo -n "${posts__not_found_header_content}" >> "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}/${defaults__default_file_name}${defaults__default_file_extension}"
+				templates__current_get_part 'top' >> "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}/${defaults__default_file_name}${defaults__default_file_extension}"
+				echo "${posts__label_not_found}" >> "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}/${defaults__default_file_name}${defaults__default_file_extension}"
+				templates__current_get_part 'bottom' >> "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}/${defaults__default_file_name}${defaults__default_file_extension}"
+				echo -n "${posts__not_found_footer_content}" >> "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}/${defaults__default_file_name}${defaults__default_file_extension}"
+
+				unset 'posts__no_posts_found_path'
+				break
+			fi
+
+			posts__list="${posts__list} ${post}"
+			if [ "${posts__list_limit_indicator}" = "${posts__posts_per_page}" ]; then
+				if "${posts__parallel_rendering}"; then
+					posts__generate_list "${posts__current_page_indicator}" "${posts__list}" &
+				else
+					posts__generate_list "${posts__current_page_indicator}" "${posts__list}"
+				fi
+
+				posts__list=''
+				posts__list_limit_indicator='1'
+				posts__current_page_indicator="$((posts__current_page_indicator+1))"
+			else
+				posts__list_limit_indicator="$((posts__list_limit_indicator+1))"
+			fi
+		done
+		[ ! "${posts__list}" = '' ] && if "${posts__parallel_rendering}"; then
+			posts__generate_list "${posts__current_page_indicator}" "${posts__list}" &
 		else
-			posts__list_limit_indicator="$((posts__list_limit_indicator+1))"
+			posts__generate_list "${posts__current_page_indicator}" "${posts__list}"
 		fi
-	done
-	[ ! "${posts__list}" = '' ] && posts__generate_list "${posts__current_page_indicator}" "${posts__list}"
 
-	unset post
-	unset posts__current_page_indicator
-	unset posts__list_limit_indicator
-	unset posts__list
+		unset 'post'
+		unset 'posts__current_page_indicator'
+		unset 'posts__list_limit_indicator'
+		unset 'posts__list'
 
-	unset posts__generate_list
+		unset 'posts__generate_list'
+	else
+		echo 'Post list generation is disabled'
+	fi
+
+	"${posts__parallel_rendering}" && wait
 
 # home page processing
-	if [ "${defaults__home_module}" = 'posts' ]; then
-		echo "This is default module - generating home page"
+	[ "${defaults__home_module}" = "${__module_name__}" ] && if "${posts__enable_post_lists}"; then
+		echo 'This is default module - generating home page'
 		if "${posts__no_first_page_mode}" && [ -e "${SSG__generated}/${posts__generated_page_directory}/${defaults__default_file_name}${defaults__default_file_extension}" ]; then
 			cp "${SSG__generated}/${posts__generated_page_directory}/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
 		elif [ -e "${SSG__generated}/${posts__generated_page_directory}1/${defaults__default_file_name}${defaults__default_file_extension}" ]; then
 			cp "${SSG__generated}/${posts__generated_page_directory}1/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
 		else
 			echo "Generating 'no posts found'"
-			template__get_part "${defaults__template}" 'top' >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
+			echo -n "${posts__not_found_header_content}" >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
+			templates__current_get_part 'top' >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
 			echo "${posts__label_not_found}" >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
-			template__get_part "${defaults__template}" 'bottom' >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
+			templates__current_get_part 'bottom' >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
+			echo -n "${posts__not_found_footer_content}" >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
 		fi
+	else
+		'Error: posts__enable_post_lists is false - this module cannot be the default module'
 	fi
 
 exit 0
diff --git a/modules/static/generate b/modules/static/generate
--- a/modules/static/generate
+++ b/modules/static/generate
@@ -1,17 +1,23 @@
 #!/usr/bin/env sh
-# copy static files to public directory
+# Copy static files to public directory
+__module_name__='static'
 
-if [ -e "${SSG__database}/static" ]; then
+static__dbdir='static'
+
+if [ -e "${SSG__database}/${static__dbdir}" ]; then
 		echo 'Copying static files'
 		[ ! -e "${SSG__generated}" ] && mkdir -p "${SSG__generated}"
-		cp -rfp ${SSG__database}/static/* "${SSG__generated}"
-		for hiddenfile in ${SSG__database}/static/.*; do
-			if [ ! "${hiddenfile}" = "${SSG__database}/static/." ] && [ ! "${hiddenfile}" = "${SSG__database}/static/.." ]; then
+		cp -rfp ${SSG__database}/${static__dbdir}/* "${SSG__generated}"
+		for hiddenfile in ${SSG__database}/${static__dbdir}/.*; do
+			if [ ! "${hiddenfile}" = "${SSG__database}/${static__dbdir}/." ] && [ ! "${hiddenfile}" = "${SSG__database}/${static__dbdir}/.." ]; then
 				cp -rfp "${hiddenfile}" "${SSG__generated}"
 			fi
 		done
 else
-	echo '"static" directory not found in database'
+	echo '"'"${static__dbdir}"'" directory not found in database'
 fi
+
+# you can't do that
+	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1
 
 exit 0
diff --git a/modules/z-a_sitemap/generate b/modules/z-a_sitemap/generate
--- a/modules/z-a_sitemap/generate
+++ b/modules/z-a_sitemap/generate
@@ -1,5 +1,6 @@
 #!/usr/bin/env sh
 # sitemap.xml generator
+__module_name__='z-a_sitemap'
 
 # defaults variables
 	. "${0%/*}/defaults.rc.d/sitemap.rc"
@@ -28,7 +29,7 @@
 	echo 'Generating sitemap...'
 
 # save sitemap.xml header
-	echo '<?xml version="1.0" encoding="UTF-8" ?>' > "${SSG__generated}/${sitemap__sitemap_file_name}"
+	echo "${sitemap__header_content}"'<?xml version="1.0" encoding="UTF-8" ?>' > "${SSG__generated}/${sitemap__sitemap_file_name}"
 	echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> "${SSG__generated}/${sitemap__sitemap_file_name}"
 
 # find ${defaults__default_file_name}${defaults__default_file_extension} files
@@ -66,7 +67,7 @@
 	done
 
 # save sitemap.xml footer
-	echo -n '</urlset>' >> "${SSG__generated}/${sitemap__sitemap_file_name}"
+	echo -n '</urlset>'"${sitemap__footer_content}" >> "${SSG__generated}/${sitemap__sitemap_file_name}"
 
 # gzip sitemap.xml
 	if [ ! "${sitemap__gzip_sitemap_xml}" = '' ]; then
@@ -85,5 +86,8 @@
 			echo "Sitemap: ${sitemap__page_domain}/${sitemap__sitemap_file_name}.gz" >> "${SSG__generated}/robots.txt"
 		fi
 	fi
+
+# you can't do that
+	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1
 
 exit 0
diff --git a/modules/z-y_minify/generate b/modules/z-y_minify/generate
--- a/modules/z-y_minify/generate
+++ b/modules/z-y_minify/generate
@@ -1,5 +1,6 @@
 #!/usr/bin/env sh
-# minificator module
+# minifier module
+__module_name__='z-y_minify'
 
 # defaults variables
 	. "${0%/*}/defaults.rc.d/minify.rc"
@@ -7,29 +8,24 @@
 # variables
 	. "${SSG__lib}/import-defaults.rc"
 
-# minify html
-	if "${minify__process_html}"; then
+# functions
+	minify_html()
+	{
 		find ${SSG__generated} -name *.html | while read file; do
 			echo "Processing $(echo -n "${file}" | sed 's|'"${SSG__generated}"'||g')"
 			sed -i -e ':a;N;$!ba;s/>\s*</></g' "${file}" # https://stackoverflow.com/questions/12376368/minify-html-files-in-text-html-templates
 		done
-	else
-		echo 'HTML minification is disabled in settings'
-	fi
-
-# minify css
-	if "${minify__process_css}"; then
+	}
+	minify_css()
+	{
 		find ${SSG__generated} -name *.css | while read file; do
 			echo "Processing $(echo -n "${file}" | sed 's|'"${SSG__generated}"'||g')"
 			sed -i -e 's/^[ \t]*//g; s/[ \t]*$//g; s/\([:{;,]\) /\1/g; s/ {/{/g; s/\/\*.*\*\///g; /^$/d' "${file}" # https://gist.github.com/dominicmartineau/5483359
 			sed -i -e :a -e '$!N; s/\n\(.\)/\1/; ta' "${file}"
 		done
-	else
-		echo 'CSS minification is disabled in settings'
-	fi
-
-# minify js
-	if "${minify__process_js}"; then
+	}
+	minify_js()
+	{
 		find ${SSG__generated} -name *.js | while read file; do
 			echo "Processing $(echo -n "${file}" | sed 's|'"${SSG__generated}"'||g')"
 			#sed -i -E 's@[[:blank:]]*(//|#).*@@;T;/./!d' "${file}" # https://unix.stackexchange.com/questions/383960/sed-stripping-comments-inline
@@ -38,8 +34,44 @@
 			sed -i -e "s/^[ \t]*//g" -e "/^$/d" "${file}" # https://stackoverflow.com/questions/12376368/minify-html-files-in-text-html-templates
 			sed -i ':a;N;$!ba;s/\n/ /g' "${file}" # https://stackoverflow.com/questions/1251999/how-can-i-replace-a-newline-n-using-sed
 		done
+	}
+
+# minify html
+	if "${minify__process_html}"; then
+		if "${minify__parallel_rendering}"; then
+			minify_html &
+		else
+			minify_html
+		fi
+	else
+		echo 'HTML minification is disabled in settings'
+	fi
+
+# minify css
+	if "${minify__process_css}"; then
+		if "${minify__parallel_rendering}"; then
+			minify_css &
+		else
+			minify_css
+		fi
+	else
+		echo 'CSS minification is disabled in settings'
+	fi
+
+# minify js
+	if "${minify__process_js}"; then
+		if "${minify__parallel_rendering}"; then
+			minify_js &
+		else
+			minify_js
+		fi
 	else
 		echo 'JS minification is disabled in settings'
 	fi
+
+"${minify__parallel_rendering}" && wait
+
+# you can't do that
+	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1
 
 exit 0
diff --git a/modules/z-z_gzip/generate b/modules/z-z_gzip/generate
--- a/modules/z-z_gzip/generate
+++ b/modules/z-z_gzip/generate
@@ -1,16 +1,32 @@
 #!/usr/bin/env sh
-# gzip wrapper module
+# Compressor module
+__module_name__='z-z_gzip'
 
 # defaults variables
-. "${0%/*}/defaults.rc.d/gzip.rc"
+	. "${0%/*}/defaults.rc.d/gzip.rc"
 
 # variables
-. "${SSG__lib}/import-defaults.rc"
+	. "${SSG__lib}/import-defaults.rc"
 
 if [ "${gzip__compression}" = '' ]; then
 	echo 'Gzip compression is disabled in settings'
 else
-	find ${SSG__generated} -name '*.html' -or -name '*.css' -or -name '*.js' | while read file; do
+	find ${SSG__generated} -name '*.html' -or -name '*.css' -or -name '*.js' -or -name '*.xml' | while read file; do
+		case "${file##*.}" in
+			'html')
+				"${gzip__process_html}" || continue
+			;;
+			'css')
+				"${gzip__process_css}" || continue
+			;;
+			'js')
+				"${gzip__process_js}" || continue
+			;;
+			'xml')
+				"${gzip__process_xml}" || continue
+			;;
+		esac
+
 		echo "Zipping $(echo -n "${file}" | sed 's|'"${SSG__generated}"'||g')"
 		gzip "-${gzip__compression}" "${file}"
 
@@ -18,5 +34,8 @@ else
 			mv "${file}.gz" "${file}"
 	done
 fi
+
+# you can't do that
+	[ "${defaults__home_module}" = "${__module_name__}" ] && echo 'Error: this module cannot be the default module' && exit 1
 
 exit 0
