Code cleaned up

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -4,16 +4,16 @@
 # Required tools for entrypoint: date dirname readlink tr sort cat mv rm
 
 echo ' :: Checking required tools'
-for tool in 'dirname' 'readlink'; do
-	echo -n "Checking '${tool}'"
+	for tool in 'dirname' 'readlink'; do
+		echo -n "Checking '${tool}'"
 
-	if command -v "${tool}" > /dev/null 2>&1; then
+		if ! command -v "${tool}" > /dev/null 2>&1; then
+			echo ' [FAIL]'
+			exit 1
+		fi
+
 		echo ' [ OK ]'
-	else
-		echo ' [FAIL]'
-		exit 1
-	fi
-done
+	done
 
 # global variables (you can rewrite in database/defaults.rc.d)
 	export SSG__root="$(dirname "$(readlink -f "${0}")")"
@@ -22,85 +22,101 @@ done
 	export SSG__user_modules="${SSG__database}/modules"
 	export SSG__generated="${SSG__root}/generated"
 	export SSG__lib="${SSG__root}/lib"
-	[ -d "${SSG__root}/bin" ] && export PATH="${SSG__root}/bin:${PATH}"
+	[ -d "${SSG__root}/bin" ] && \
+		export PATH="${SSG__root}/bin:${PATH}"
 
 # execution time measurement (1)
-	entrypointStartTime="$(date '+%s')"
+	entrypoint_start_time="$(date '+%s')"
 
 # local variables
-	entrypointCheckModules='true'
-	entrypointCheckTools='true'
+	entrypoint_check_modules='true'
+	entrypoint_check_tools='true'
 	. "${SSG__lib}/import-defaults.rc"
 
 # functions
 	check_disabled_modules()
 	{
 		local module
+
 		for module in ${2}; do
 			[ "${1}" = "${module}" ] && return '1'
 		done
+
 		return '0'
 	}
 
 # tools check
-	if "${entrypointCheckTools}"; then
+	if "${entrypoint_check_tools}"; then
 		echo ' :: Checking required tools'
-		moduleRequiredTools='date tr sort cat mv rm' # for entrypoint
+		module_required_tools='date tr sort cat mv rm' # for entrypoint
 
 		for module in ${SSG__modules}/* ${SSG__user_modules}/*; do
 			[ "${module}" = "${SSG__modules}/*" ] && continue
 			[ "${module}" = "${SSG__user_modules}/*" ] && break
-			[ -e "${module}/command-stack" ] && check_disabled_modules "${module##*/}" "${defaults__disabled_modules}" && moduleRequiredTools="${moduleRequiredTools} $(cat "${module}/command-stack")"
+
+			[ -e "${module}/command-stack" ] && \
+				check_disabled_modules "${module##*/}" "${defaults__disabled_modules}" && \
+				module_required_tools="${module_required_tools} $(cat "${module}/command-stack")"
 		done
 
-		if [ ! "${moduleRequiredTools}" = '' ]; then
-			moduleRequiredTools="$(echo -n "${moduleRequiredTools}" | tr ' ' '\n' | sort -u)"
+		if [ ! "${module_required_tools}" = '' ]; then
+			module_required_tools="$(echo -n "${module_required_tools}" | tr ' ' '\n' | sort -u)"
 
-			for tool in ${moduleRequiredTools}; do
+			for tool in ${module_required_tools}; do
 				echo -n "Checking '${tool}'"
 
-				if command -v "${tool}" > /dev/null 2>&1; then
-					echo ' [ OK ]'
-				else
+				if ! command -v "${tool}" > /dev/null 2>&1; then
 					echo ' [FAIL]'
+
 					echo -n 'Continue anyway? (y/[N]) '
 					read answer
 					[ ! "${answer}" = 'y' ] && exit 1
 					unset 'answer'
+
 					break
 				fi
+
+				echo ' [ OK ]'
 			done
 		fi
 
-		unset 'moduleRequiredTools'
+		unset 'module_required_tools'
 		unset 'tool'
 	fi
 
 # module dependencies check
-	if "${entrypointCheckModules}"; then
+	if "${entrypoint_check_modules}"; then
 		echo ' :: Checking modules dependencies'
+
 		for module in ${SSG__modules}/* ${SSG__user_modules}/*; do
 			[ "${module}" = "${SSG__modules}/*" ] && continue
-			if [ -e "${module}/dependencies" ] && check_disabled_modules "${module##*/}" "${defaults__disabled_modules}"; then
-				echo -n "Checking module ${module##*/}"
-				if ! \
-					cat "${module}/dependencies" | while read dependentModule; do
-						if [ ! -e "${SSG__modules}/${dependentModule}" ]; then
-							echo -n " (failed on ${dependentModule} module) "
-							exit 1
-						fi
-					done
-				then
-					echo ' [FAIL]'
-					echo -n 'Continue anyway? (y/[N]) '
-					read answer
-					[ ! "${answer}" = 'y' ] && exit 1
-					unset 'answer'
-					break
-				else
-					echo ' [ OK ]'
-				fi
+			[ "${module}" = "${SSG__user_modules}/*" ] && break
+
+			if [ ! -e "${module}/dependencies" ] || ! check_disabled_modules "${module##*/}" "${defaults__disabled_modules}"; then
+				continue
 			fi
+
+			echo -n "Checking module ${module##*/}"
+
+			if ! \
+				cat "${module}/dependencies" | while read 'dependent_module'; do
+					if [ ! -e "${SSG__modules}/${dependent_module}" ] && [ ! -e "${SSG__user_modules}/${dependent_module}" ]; then
+						echo -n " (failed on ${dependent_module} module) "
+						exit 1
+					fi
+				done
+			then
+				echo ' [FAIL]'
+
+				echo -n 'Continue anyway? (y/[N]) '
+				read answer
+				[ ! "${answer}" = 'y' ] && exit 1
+				unset 'answer'
+
+				break
+			fi
+
+			echo ' [ OK ]'
 		done
 	fi
 
@@ -121,25 +137,26 @@ fi
 # modules generators
 	for module in ${SSG__modules}/* ${SSG__user_modules}/*; do
 		[ "${module}" = "${SSG__modules}/*" ] && echo 'No modules installed'
-		if [ -x "${module}/generate" ]; then
-			moduleName="${module##*/}"
-			if check_disabled_modules "${moduleName}" "${defaults__disabled_modules}"; then
-				echo " :: Running ${moduleName} module"
-				"${module}/generate"
-				if [ "$?" = '0' ]; then
-					echo " :: ${moduleName} module ended"
-				else
-					echo " :: ${moduleName} module failed"
-				fi
+		[ ! -x "${module}/generate" ] && continue
 
-				if [ -e "${SSG__generated}/.reimport-defaults" ]; then
-					echo ' :: Re-importing defaults variables'
-					. "${SSG__lib}/import-defaults.rc"
-					rm "${SSG__generated}/.reimport-defaults"
-				fi
-			else
-				echo " :: ${moduleName} module is disabled"
-			fi
+		module_name="${module##*/}"
+
+		if ! check_disabled_modules "${module_name}" "${defaults__disabled_modules}"; then
+			echo " :: ${module_name} module is disabled"
+			continue
+		fi
+
+		echo " :: Running ${module_name} module"
+		"${module}/generate"
+
+		[ "$?" = '0' ] && \
+			echo " :: ${module_name} module ended" || \
+			echo " :: ${module_name} module failed"
+
+		if [ -e "${SSG__generated}/.reimport-defaults" ]; then
+			echo ' :: Re-importing defaults variables'
+			. "${SSG__lib}/import-defaults.rc"
+			rm "${SSG__generated}/.reimport-defaults"
 		fi
 	done
 
@@ -149,16 +166,16 @@ if [ -e "${SSG__database}/generate-hooks/post-generate.rc" ]; then
 fi
 
 # default module check
-	if [ "${defaults__home_module}" = '' ]; then
-		echo "error: default module '${defaults__home_module}' is not defined"
+	[ "${defaults__home_module}" = '' ] && \
+		echo "error: default module '${defaults__home_module}' is not defined" && \
 		exit 1
-	fi
-	if [ ! -e "${SSG__modules}/${defaults__home_module}" ] && [ ! -e "${SSG__user_modules}/${defaults__home_module}" ]; then
-		echo "error: default module '${defaults__home_module}' not found in modules"
+
+	[ ! -e "${SSG__modules}/${defaults__home_module}" ] && [ ! -e "${SSG__user_modules}/${defaults__home_module}" ] && \
+		echo "error: default module '${defaults__home_module}' not found in modules" && \
 		exit 1
-	fi
 
 # execution time measurement (2)
-	[ ! "${entrypointStartTime}" = '' ] && echo " :: Script executed in $(($(date '+%s')-entrypointStartTime)) seconds"
+	[ ! "${entrypoint_start_time}" = '' ] && \
+		echo " :: Script executed in $(($(date '+%s')-entrypoint_start_time)) seconds"
 
 exit 0
diff --git a/modules/pages/generate b/modules/pages/generate
--- a/modules/pages/generate
+++ b/modules/pages/generate
@@ -1,5 +1,6 @@
 #!/usr/bin/env sh
 # Pages generator module
+[ ! "${@}" = '' ] && exit 1
 __module_name__='pages'
 
 # defaults variables
@@ -11,84 +12,101 @@ __module_name__='pages'
 	. "${SSG__lib}/import-defaults.rc"
 
 # directory in database
-	if [ ! -e "${SSG__database}/${pages__dbdir}" ]; then
-		echo '"'"${pages__dbdir}"'" directory not found in database'
+	[ ! -e "${SSG__database}/${pages__dbdir}" ] && \
+		echo '"'"${pages__dbdir}"'" directory not found in database' && \
 		exit 1
-	fi
 
 # functions
 	pages__render_script()
 	{
 		local script="${entrypoint%/*}/${1}"
-		local scriptPath="$(echo -n "${script}" | sed 's|'"${SSG__database}/${pages__dbdir}/"'||g')"
-		local renderedScriptPathSubpath="${3}"; [ ! "${renderedScriptPathSubpath}" = '' ] && renderedScriptPathSubpath="/${renderedScriptPathSubpath}"
-		local renderedScriptPath="${SSG__generated}/${pages__generated_directory}${scriptPath%/*}${renderedScriptPathSubpath}"
+		local script_path="$(echo -n "${script}" | sed 's|'"${SSG__database}/${pages__dbdir}/"'||g')"
 
-		[ -e "${renderedScriptPath}" ] && echo "error: directory conflict on ${pages__generated_directory}${scriptPath%/*}"
+		local rendered_script_path_subpath="${3}"
+		[ ! "${rendered_script_path_subpath}" = '' ] && \
+			rendered_script_path_subpath="/${rendered_script_path_subpath}"
 
-		echo " Generating script ${scriptPath}"
-		[ ! -e "${renderedScriptPath}" ] && mkdir -p "${renderedScriptPath}"
-		. "${script}" >> "${renderedScriptPath}/${2}"
+		local rendered_script_path="${SSG__generated}/${pages__generated_directory}${script_path%/*}${rendered_script_path_subpath}"
+
+		[ -e "${rendered_script_path}" ] && \
+			echo "error: directory conflict on ${pages__generated_directory}${script_path%/*}"
+
+		echo " Generating script ${script_path}"
+
+		[ ! -e "${rendered_script_path}" ] && \
+			mkdir -p "${rendered_script_path}"
+
+		. "${script}" >> "${rendered_script_path}/${2}"
 	}
 	pages__copy_file()
 	{
-		local scriptLocation="${entrypoint%/*}"
+		local script_location="${entrypoint%/*}"
 
-		if [ "${renderedScriptPath}" = '' ]; then
-			local scriptPath="$(echo -n "${entrypoint%/*}" | sed 's|'"${SSG__database}/${pages__dbdir}/"'||g')"
-			local renderedScriptPath="${SSG__generated}/${pages__generated_directory}${scriptPath%/*}"
+		if [ "${rendered_script_path}" = '' ]; then
+			local script_path="$(echo -n "${entrypoint%/*}" | sed 's|'"${SSG__database}/${pages__dbdir}/"'||g')"
+			local rendered_script_path="${SSG__generated}/${pages__generated_directory}${script_path%/*}"
 		fi
 
-		if [ -e "${scriptLocation}/${1}" ]; then
-			if [ -f "${scriptLocation}/${1}" ]; then
-				echo " Copying file '${1}' to '${2}'" >&2
-			elif [ -d "${scriptLocation}/${1}" ]; then
-				echo " Copying directory '${1}' to '${2}'" >&2
-			else
-				echo " Copying '${1}' to '${2}'" >&2
-			fi
+		if [ ! -e "${script_location}/${1}" ]; then
+			echo "   File ${script_location}/${1} not exists" >&2
+			return
+		fi
 
-			[ ! -e "${renderedScriptPath}" ] && mkdir "${renderedScriptPath}"
-			cp -r "${scriptLocation}/${1}" "${renderedScriptPath}/${2}"
+		if [ -f "${script_location}/${1}" ]; then
+			echo "  Copying file '${1}' to '${2}'" >&2
+		elif [ -d "${script_location}/${1}" ]; then
+			echo "  Copying directory '${1}' to '${2}'" >&2
 		else
-			echo "  File ${scriptLocation}/${1} not exists" >&2
+			echo "  Copying '${1}' to '${2}'" >&2
 		fi
+
+		[ ! -e "${rendered_script_path}" ] && \
+			mkdir "${rendered_script_path}"
+
+		cp -r "${script_location}/${1}" "${rendered_script_path}/${2}"
 	}
 
 # database processing
 	for page in ${SSG__database}/${pages__dbdir}/*; do
 		[ "${page}" = "${SSG__database}/${pages__dbdir}/*" ] && break
+		[ ! -d "${page}" ] && continue
 
-		if [ -d "${page}" ]; then
-			echo "Generating page '${page##*/}'"
-			if "${pages__parallel_rendering}"; then
-				find "${page}" -name 'entrypoint.rc' | while read entrypoint; do
-					unset 'page'
-					. "${entrypoint}"
-				done &
-			else
-				find "${page}" -name 'entrypoint.rc' | while read entrypoint; do
-					unset 'page'
-					. "${entrypoint}"
-				done
-			fi
+		echo "Generating page '${page##*/}'"
+
+		if "${pages__parallel_rendering}"; then
+			find "${page}" -name 'entrypoint.rc' | while read 'entrypoint'; do
+				unset 'page'
+				. "${entrypoint}"
+			done &
+
+			continue
 		fi
+
+		find "${page}" -name 'entrypoint.rc' | while read 'entrypoint'; do
+			unset 'page'
+			. "${entrypoint}"
+		done
 	done
+
 	"${pages__parallel_rendering}" && wait
 
 # home page processing
 	. "${SSG__lib}/import-includes.rc"
+
 	[ "${defaults__home_module}" = "${__module_name__}" ] && if [ "${pages__default_page}" = '' ]; then
 		echo 'pages__default_page is empty - home page not copied'
-	else
-		echo "This is default module - moving '${pages__default_page}' page"
-
-		if [ -e "${SSG__generated}/${pages__generated_directory}${pages__default_page}/${defaults__default_file_name}${defaults__default_file_extension}" ]; then
-			mv "${SSG__generated}/${pages__generated_directory}${pages__default_page}/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
-			rmdir "${SSG__generated}/${pages__generated_directory}${pages__default_page}" # will be failed if other files were copied
-		else
-			echo "${pages__generated_directory}${pages__default_page}/${defaults__default_file_name}${defaults__default_file_extension} not found in generated files"
-		fi
+		exit 0
 	fi
+
+	echo "This is default module - moving '${pages__default_page}' page"
+
+	if [ -e "${SSG__generated}/${pages__generated_directory}${pages__default_page}/${defaults__default_file_name}${defaults__default_file_extension}" ]; then
+		mv "${SSG__generated}/${pages__generated_directory}${pages__default_page}/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
+		rmdir "${SSG__generated}/${pages__generated_directory}${pages__default_page}" # will be failed if other files were copied
+
+		exit 0
+	fi
+
+	echo "${pages__generated_directory}${pages__default_page}/${defaults__default_file_name}${defaults__default_file_extension} not found in generated files"
 
 exit 0
diff --git a/modules/posts-arch/generate b/modules/posts-arch/generate
--- a/modules/posts-arch/generate
+++ b/modules/posts-arch/generate
@@ -1,5 +1,6 @@
 #!/usr/bin/env sh
 # Post archive generator module
+[ ! "${@}" = '' ] && exit 1
 __module_name__='posts-arch'
 
 # defaults variables
@@ -13,37 +14,7 @@ __module_name__='posts-arch'
 	[ "${posts_arch__generated_directory}" = '' ] && posts_arch__generated_directory='arch'
 
 # functions
-	generatePostBox()
-	{
-		if [ ! "${1}" = 'noTitleLink' ]; then  # for post metadata
-			. "${post}/meta.rc"
-			template__no_title_link='false'
-		else
-			template__no_title_link='true'
-		fi
-
-		if [ -e "${post}/tags" ]; then
-			local tag
-			local posts__post_tags
-			for tag in ${post}/tags/*; do
-				[ "${tag}" = "${post}/tags/*" ] && break
-				posts__post_tags="${posts__post_tags} #${tag##*/}"
-			done
-			posts__post_tags="${posts__post_tags#?}"
-			unset 'tag'
-		fi
-
-		if ! templates__current_get_part 'resource' 'posts-content'; then
-			echo "error: template ${templates__template} does not provide posts-content.rc" >&2
-		fi
-
-		unset 'posts__post_title'
-		unset 'posts__post_date'
-		unset 'posts__post_id'
-		unset 'posts__post_tags'
-
-		unset 'template__no_title_link'
-	}
+	. "${0%/*}/../posts/generate_post_box.rc"
 
 # directory in database
 	if [ ! -e "${SSG__database}/${posts__dbdir}" ]; then
@@ -53,21 +24,28 @@ __module_name__='posts-arch'
 
 # database processing
 	post_arch__date_list=''
+
 	for post in ${SSG__database}/${posts__dbdir}/public_*; do
 		[ "${post}" = "${SSG__database}/${posts__dbdir}/public_*" ] && break
+
 		for post_arch in ${post}/arch_*; do
 			[ "${post_arch}" = "${post}/arch_*" ] && break
+
 			post_arch=${post_arch##*/}
 			post_arch__date_list="${post_arch#*_} ${post_arch__date_list}"
 		done
 	done
-	[ ! "${post_arch__date_list}" = '' ] && post_arch__date_list="$(echo -n "${post_arch__date_list}" | tr ' ' '\n' | uniq)" # deduplicate date list
+
+	# deduplicate date list
+	[ ! "${post_arch__date_list}" = '' ] && \
+		post_arch__date_list="$(echo -n "${post_arch__date_list}" | tr ' ' '\n' | uniq)"
 
 # date list processing
 	posts_arch__generate_date_list()
 	{
 		local template__html_headers="${posts_arch__list_html_headers}"
 		posts_arch__html_title
+
 		echo -n "${posts_arch__list_header_content}"
 		templates__current_get_part 'top'
 
@@ -78,7 +56,9 @@ __module_name__='posts-arch'
 		templates__current_get_part 'bottom'
 		echo -n "${posts_arch__list_footer_content}"
 	}
+
 	[ ! -e "${SSG__generated}/${posts_arch__generated_directory}" ] && mkdir -p "${SSG__generated}/${posts_arch__generated_directory}"
+
 	if "${posts_arch__enable_date_lists}"; then
 		if "${posts_arch__parallel_rendering}"; then
 			posts_arch__generate_date_list >> "${SSG__generated}/${posts_arch__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}" &
@@ -93,64 +73,74 @@ __module_name__='posts-arch'
 	if [ ! "${post_arch__date_list}" = '' ]; then
 		posts_arch__generate_list()
 		{
-			local currentPostNumber='1'
-			local currentPageNumber='1'
-			local renderedPageDirNumber=''
 			local post
+			local rendered_post
+			local current_post_number='1'
+			local current_page_number='1'
+			local rendered_page_dir_number=''
 
 			for post in ${1}; do
 				post="${post%/*}"
-				if [ ! "${currentPageNumber}" = '1' ] && [ "${currentPostNumber}" = '1' ]; then
-					renderedPageDirNumber="/${currentPageNumber}"
-					mkdir "${renderedPageDir}${renderedPageDirNumber}"
+
+				if [ ! "${current_page_number}" = '1' ] && [ "${current_post_number}" = '1' ]; then
+					rendered_page_dir_number="/${current_page_number}"
+					mkdir "${rendered_page_dir}${rendered_page_dir_number}"
 				fi
 
-				if [ "${currentPostNumber}" = '1' ]; then
-					echo " Processing page ${currentPageNumber}"
+				if [ "${current_post_number}" = '1' ]; then
+					echo " Processing page ${current_page_number}"
+
 					template__html_headers="${posts_arch__listing_html_headers}"
 					posts_arch__list_html_title
-					echo -n "${posts_arch__listing_header_content}" >> "${renderedPageDir}${renderedPageDirNumber}/${defaults__default_file_name}${defaults__default_file_extension}"
-					templates__current_get_part 'top' >> "${renderedPageDir}${renderedPageDirNumber}/${defaults__default_file_name}${defaults__default_file_extension}"
+
+					echo -n "${posts_arch__listing_header_content}" >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
+					templates__current_get_part 'top' >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
 				fi
 
-				echo "  Adding post ${post##*/}"
-				local renderedPost="${post##*_}"
-				generatePostBox >> "${renderedPageDir}${renderedPageDirNumber}/${defaults__default_file_name}${defaults__default_file_extension}"
+				rendered_post="${post##*_}"
+				echo "  Adding post ${rendered_post}"
+				generate_post_box >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
 
-				if [ "${currentPostNumber}" = "${posts__posts_per_page}" ]; then
-					if ! templates__current_get_part 'resource' 'arch-pages' >> "${renderedPageDir}${renderedPageDirNumber}/${defaults__default_file_name}${defaults__default_file_extension}"; then
+				if [ "${current_post_number}" = "${posts__posts_per_page}" ]; then
+					if ! templates__current_get_part 'resource' 'arch-pages' >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"; then
 						echo "error: template ${templates__template} does not provide arch-pages.rc"
 					fi
 
-					templates__current_get_part 'bottom' >> "${renderedPageDir}${renderedPageDirNumber}/${defaults__default_file_name}${defaults__default_file_extension}"
-					echo -n "${posts_arch__listing_footer_content}" >> "${renderedPageDir}${renderedPageDirNumber}/${defaults__default_file_name}${defaults__default_file_extension}"
+					templates__current_get_part 'bottom' >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
+					echo -n "${posts_arch__listing_footer_content}" >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
 
-					currentPostNumber='1'
-					currentPageNumber="$((currentPageNumber+1))"
-				else
-					currentPostNumber="$((currentPostNumber+1))"
+					current_post_number='1'
+					current_page_number="$((current_page_number+1))"
+
+					continue
 				fi
+
+				current_post_number="$((current_post_number+1))"
 			done
-			if [ ! "${currentPostNumber}" = "${posts__posts_per_page}" ] && [ ! "${currentPostNumber}" = '1' ]; then
-				if ! templates__current_get_part 'resource' 'arch-pages' >> "${renderedPageDir}${renderedPageDirNumber}/${defaults__default_file_name}${defaults__default_file_extension}"; then
+
+			if [ ! "${current_post_number}" = "${posts__posts_per_page}" ] && [ ! "${current_post_number}" = '1' ]; then
+				if ! templates__current_get_part 'resource' 'arch-pages' >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"; then
 					echo "error: template ${templates__template} does not provide arch-pages.rc"
 				fi
 
-				templates__current_get_part 'bottom' >> "${renderedPageDir}${renderedPageDirNumber}/${defaults__default_file_name}${defaults__default_file_extension}"
-				echo -n "${posts_arch__listing_footer_content}" >> "${renderedPageDir}${renderedPageDirNumber}/${defaults__default_file_name}${defaults__default_file_extension}"
+				templates__current_get_part 'bottom' >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
+				echo -n "${posts_arch__listing_footer_content}" >> "${rendered_page_dir}${rendered_page_dir_number}/${defaults__default_file_name}${defaults__default_file_extension}"
 			fi
 		}
 
 		for date in ${post_arch__date_list}; do
 			echo "Processing date ${date}"
-			renderedPageDir="${SSG__generated}/${posts_arch__generated_directory}/${date}"
-			mkdir "${renderedPageDir}"
+
+			rendered_page_dir="${SSG__generated}/${posts_arch__generated_directory}/${date}"
+			mkdir "${rendered_page_dir}"
 
 			posts_arch__counted_posts='0'
 			posts_arch__counted_posts_find="$(find ${SSG__database}/${posts__dbdir}/public_* -type f -path "*/arch_${date}" | tac)" # cache
+
 			for post in ${posts_arch__counted_posts_find}; do
 				posts_arch__counted_posts="$((posts_arch__counted_posts+1))"
 			done
+
 			posts_arch__counted_pages="$(awk '
 				BEGIN {
 					printf \
@@ -161,10 +151,12 @@ __module_name__='posts-arch'
 
 			if "${posts_arch__parallel_rendering}"; then
 				posts_arch__generate_list "${posts_arch__counted_posts_find}" &
-			else
-				posts_arch__generate_list "${posts_arch__counted_posts_find}"
+				continue
 			fi
+
+			posts_arch__generate_list "${posts_arch__counted_posts_find}"
 		done
+
 		"${posts_arch__parallel_rendering}" && wait
 	fi
 
@@ -173,7 +165,8 @@ __module_name__='posts-arch'
 		echo 'This is default module - generating home page'
 		mv "${SSG__generated}/${posts_arch__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
 	else
-		'Error: posts_arch__enable_date_lists is false - this module cannot be the default module'
+		echo 'Error: posts_arch__enable_date_lists is false - this module cannot be the default module'
+		exit 1
 	fi
 
 exit 0
diff --git a/modules/posts-tags/generate b/modules/posts-tags/generate
--- a/modules/posts-tags/generate
+++ b/modules/posts-tags/generate
@@ -1,5 +1,6 @@
 #!/usr/bin/env sh
 # Tag list generator module
+[ ! "${@}" = '' ] && exit 1
 __module_name__='posts-tags'
 
 # defaults variables
@@ -20,46 +21,18 @@ __module_name__='posts-tags'
 	fi
 
 # functions
-	generatePostBox()
-	{
-		if [ ! "${1}" = 'noTitleLink' ]; then  # for post metadata
-			. "${post}/meta.rc"
-			template__no_title_link='false'
-		else
-			template__no_title_link='true'
-		fi
-
-		if [ -e "${post}/tags" ]; then
-			local tag
-			local posts__post_tags
-			for tag in ${post}/tags/*; do
-				[ "${tag}" = "${post}/tags/*" ] && break
-				posts__post_tags="${posts__post_tags} #${tag##*/}"
-			done
-			posts__post_tags="${posts__post_tags#?}"
-			unset 'tag'
-		fi
-
-		if ! templates__current_get_part 'resource' 'posts-content'; then
-			echo "error: template ${templates__template} does not provide posts-content.rc" >&2
-		fi
-
-		unset 'posts__post_title'
-		unset 'posts__post_date'
-		unset 'posts__post_id'
-		unset 'posts__post_tags'
-
-		unset 'template__no_title_link'
-	}
+	. "${0%/*}/../posts/generate_post_box.rc"
 
 # database processing - read all tags
 	for post in ${SSG__database}/${posts__dbdir}/public_*; do
 		[ "${post}" = "${SSG__database}/${posts__dbdir}/public_*" ] && break
+
 		for tag in ${post}/tags/*; do
 			[ "${tag}" = "${post}/tags/*" ] && break
 			posts__tag_list="${posts__tag_list} ${tag##*/}"
 		done
 	done
+
 	[ ! "${posts__tag_list}" = '' ] && posts__tag_list="$(echo -n "${posts__tag_list}" | tr ' ' '\n' | sort -u)" # sort tag list
 
 # tag list processing
@@ -67,6 +40,7 @@ __module_name__='posts-tags'
 	{
 		local template__html_headers="${posts_tags__list_html_headers}"
 		posts_tags__html_title
+
 		echo -n "${posts_tags__list_header_content}"
 		templates__current_get_part 'top'
 
@@ -77,7 +51,9 @@ __module_name__='posts-tags'
 		templates__current_get_part 'bottom'
 		echo -n "${posts_tags__list_footer_content}"
 	}
+
 	[ ! -e "${SSG__generated}/${posts_tags__generated_directory}" ] && mkdir -p "${SSG__generated}/${posts_tags__generated_directory}"
+
 	if "${posts_tags__enable_tag_lists}"; then
 		if "${posts_tags__parallel_rendering}"; then
 			posts_tags__generate_tag_list >> "${SSG__generated}/${posts_tags__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}" &
@@ -95,38 +71,44 @@ __module_name__='posts-tags'
 			echo " Processing page ${1}"
 
 			local post
-			local currentPageNumber="${1}" # for template
+			local current_page_number="${1}" # for template
+			local rendered_post
+			local rendered_page_dir
 			local template__html_headers="${posts_tags__listing_html_headers}"
-			local template__html_title; posts_tags__list_html_title
+			local template__html_title
+
+			posts_tags__list_html_title
 
 			# cache
-			if [ "${currentPageNumber}" = '1' ]; then
-				local renderedPageDir="${SSG__generated}/${posts_tags__generated_directory}/${tag}"
+			if [ "${current_page_number}" = '1' ]; then
+				rendered_page_dir="${SSG__generated}/${posts_tags__generated_directory}/${tag}"
 			else
-				local renderedPageDir="${SSG__generated}/${posts_tags__generated_directory}/${tag}/${1}"
+				rendered_page_dir="${SSG__generated}/${posts_tags__generated_directory}/${tag}/${1}"
 			fi
 
-			[ ! -e "${renderedPageDir}" ] && mkdir -p "${renderedPageDir}"
+			[ ! -e "${rendered_page_dir}" ] && mkdir -p "${rendered_page_dir}"
 
-			echo -n "${posts_tags__listing_header_content}" >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-			templates__current_get_part 'top' >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			echo -n "${posts_tags__listing_header_content}" >> "${rendered_page_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			templates__current_get_part 'top' >> "${rendered_page_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
 
 			for post in ${2}; do
-				postName="${post##*/}"
-				echo "  Adding post ${postName##*_}"
-				unset 'postName'
+				post_name="${post##*/}"
+				echo "  Adding post ${post_name##*_}"
+				unset 'post_name'
 
-				local renderedPost="${post##*_}"
-				generatePostBox >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-				unset 'renderedPost'
+				rendered_post="${post##*_}"
+
+				generate_post_box >> "${rendered_page_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
+
+				unset 'rendered_post'
 			done
 
-			if ! templates__current_get_part 'resource' 'tags-pages' >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"; then
+			if ! templates__current_get_part 'resource' 'tags-pages' >> "${rendered_page_dir}/${defaults__default_file_name}${defaults__default_file_extension}"; then
 				echo "error: template ${templates__template} does not provide tags-pages.rc"
 			fi
 
-			templates__current_get_part 'bottom' >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-			echo -n "${posts_tags__listing_footer_content}" >> "${renderedPageDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			templates__current_get_part 'bottom' >> "${rendered_page_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			echo -n "${posts_tags__listing_footer_content}" >> "${rendered_page_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
 		}
 
 		for tag in ${posts__tag_list}; do
@@ -135,12 +117,13 @@ __module_name__='posts-tags'
 			posts_tags__list=''
 			posts_tags__list_limit_indicator='1'
 			posts_tags__current_page_indicator='1'
-
 			posts_tags__counted_posts='0'
 			posts_tags__counted_posts_find="$(find ${SSG__database}/${posts__dbdir}/public_* -type f -path "*/tags/${tag}")" # cache
+
 			for post in ${posts_tags__counted_posts_find}; do
 				posts_tags__counted_posts="$((posts_tags__counted_posts+1))"
 			done
+
 			posts_tags__counted_pages="$(awk '
 				BEGIN {
 					printf \
@@ -148,7 +131,7 @@ __module_name__='posts-tags'
 						('"${posts_tags__counted_posts}"'/'"${posts__posts_per_page}"')+0.9 \
 				}
 			')"
-			unset 'post'
+
 			unset 'posts_tags__counted_posts'
 
 			for post in $(echo "${posts_tags__counted_posts_find}" | tac); do
@@ -165,10 +148,13 @@ __module_name__='posts-tags'
 					posts_tags__list=''
 					posts_tags__list_limit_indicator='1'
 					posts_tags__current_page_indicator="$((posts_tags__current_page_indicator+1))"
-				else
-					posts_tags__list_limit_indicator="$((posts_tags__list_limit_indicator+1))"
+
+					continue
 				fi
+
+				posts_tags__list_limit_indicator="$((posts_tags__list_limit_indicator+1))"
 			done
+
 			[ ! "${posts_tags__list}" = '' ] && if "${posts_tags__parallel_rendering}"; then
 				posts_tags__generate_list "${posts_tags__current_page_indicator}" "${posts_tags__list}" &
 			else
@@ -183,9 +169,6 @@ __module_name__='posts-tags'
 		done
 
 		"${posts_tags__parallel_rendering}" && wait
-
-		unset 'posts_tags__generate_list'
-		unset 'tag'
 	fi
 
 # home page processing
@@ -193,7 +176,8 @@ __module_name__='posts-tags'
 		echo 'This is default module - generating home page'
 		mv "${SSG__generated}/${posts_tags__generated_directory}/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
 	else
-		'Error: posts_tags__enable_tag_lists is false - this module cannot be the default module'
+		echo 'Error: posts_tags__enable_tag_lists is false - this module cannot be the default module'
+		exit 1
 	fi
 
 exit 0
diff --git a/modules/posts/generate b/modules/posts/generate
--- a/modules/posts/generate
+++ b/modules/posts/generate
@@ -1,5 +1,6 @@
 #!/usr/bin/env sh
 # Post generator module
+[ ! "${@}" = '' ] && exit 1
 __module_name__='posts'
 
 # defaults variables
@@ -7,67 +8,46 @@ __module_name__='posts'
 	. "${0%/*}/defaults.rc.d/posts.rc"
 
 # variables
-	posts__ind='1'; posts__ind_pages='1'; posts__page='1' # indicators
+	posts__ind='1'
+	posts__ind_pages='1'
+	posts__page='1'
+
 	. "${SSG__lib}/import-includes.rc"
 	. "${SSG__lib}/import-defaults.rc"
 
 # directory in database
-	if [ ! -e "${SSG__database}/${posts__dbdir}" ]; then
-		echo '"'"${posts__dbdir}"'" directory not found in database'
+	[ ! -e "${SSG__database}/${posts__dbdir}" ] && \
+		echo '"'"${posts__dbdir}"'" directory not found in database' && \
 		exit 1
-	fi
 
 # functions
+	. "${0%/*}/generate_post_box.rc"
 	posts__copy_file()
 	{
-		[ ! -e "${renderedPostDir}/${2}" ] && if [ -e "${post}/${1}" ]; then
-			if [ -f "${post}/${1}" ]; then
-				echo " Copying file '${1}' to '${2}'" >&2
-			elif [ -d "${post}/${1}" ]; then
-				echo " Copying directory '${1}' to '${2}'" >&2
-			else
-				echo " Copying '${1}' to '${2}'" >&2
-			fi
-
-			cp -r "${post}/${1}" "${renderedPostDir}/${2}"
-		else
+		if [ ! -e "${post}/${1}" ]; then
 			echo "  File ${post}/${1} not exists" >&2
+			return
 		fi
-	}
-	generatePostBox()
-	{
-		if [ ! "${1}" = 'noTitleLink' ]; then  # for post metadata
-			. "${post}/meta.rc"
-			template__no_title_link='false'
+
+		if [ -e "${rendered_post_dir}/${2}" ]; then
+			echo "  File ${2} already exists in ${rendered_post_dir}" >&2
+			return
+		fi
+
+		if [ -f "${post}/${1}" ]; then
+			echo " Copying file '${1}' to '${2}'" >&2
+		elif [ -d "${post}/${1}" ]; then
+			echo " Copying directory '${1}' to '${2}'" >&2
 		else
-			template__no_title_link='true'
+			echo " Copying '${1}' to '${2}'" >&2
 		fi
 
-		if [ -e "${post}/tags" ]; then
-			local tag
-			local posts__post_tags
-			for tag in ${post}/tags/*; do
-				[ "${tag}" = "${post}/tags/*" ] && break
-				posts__post_tags="${posts__post_tags} #${tag##*/}"
-			done
-			posts__post_tags="${posts__post_tags#?}"
-			unset 'tag'
-		fi
-
-		if ! templates__current_get_part 'resource' 'posts-content'; then
-			echo "error: template ${templates__template} does not provide posts-content.rc" >&2
-		fi
-
-		unset 'posts__post_title'
-		unset 'posts__post_date'
-		unset 'posts__post_id'
-		unset 'posts__post_tags'
-
-		unset 'template__no_title_link'
+		cp -r "${post}/${1}" "${rendered_post_dir}/${2}"
 	}
 
 # database preprocessing - count pages
 	posts__counted_posts='1'
+
 	for post in ${SSG__database}/${posts__dbdir}/public_*; do
 		[ "${post}" = "${SSG__database}/${posts__dbdir}/public_*" ] && break
 		posts__counted_posts="$((posts__counted_posts+1))"
@@ -85,23 +65,29 @@ __module_name__='posts'
 	unset 'posts__counted_posts'
 
 # database processing
-	generateForPost()
+	generate_for_post()
 	{
-		postName="${post##*/}"
-		echo "Generating ${1} post ${postName##*_}"
-		unset 'postName'
+		local post_name="${post##*/}"
+		echo "Generating ${1} post ${post_name##*_}"
+		unset 'post_name'
 
-		renderedPostDir="${post##*/}"; renderedPostDir="${renderedPostDir##*_}"; renderedPostDir="${SSG__generated}/${posts__generated_post_directory}${renderedPostDir}" # cache
-		[ ! -e "${renderedPostDir}" ] && mkdir -p "${renderedPostDir}"
+		# cache
+		local rendered_post_dir="${post##*/}"
+		rendered_post_dir="${rendered_post_dir##*_}"
+		rendered_post_dir="${SSG__generated}/${posts__generated_post_directory}${rendered_post_dir}"
 
-		. "${post}/meta.rc" # for template settings
+		[ ! -e "${rendered_post_dir}" ] && mkdir -p "${rendered_post_dir}"
+
+		. "${post}/meta.rc"
 		posts__post_html_title
 
-		echo -n "${posts__post_header_content}" >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-		templates__current_get_part 'top' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-		generatePostBox 'noTitleLink' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-		templates__current_get_part 'bottom' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-		echo -n "${posts__post_footer_content}" >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		echo -n "${posts__post_header_content}" >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		templates__current_get_part 'top' >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
+
+		generate_post_box 'no_title_link' >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
+
+		templates__current_get_part 'bottom' >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
+		echo -n "${posts__post_footer_content}" >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
 	}
 
 	for post in ${SSG__database}/${posts__dbdir}/public_*; do
@@ -111,25 +97,27 @@ __module_name__='posts'
 		fi
 
 		if "${posts__parallel_rendering}"; then
-			generateForPost 'published' &
-		else
-			generateForPost 'published'
+			generate_for_post 'published' &
+			continue
 		fi
+
+		generate_for_post 'published'
 	done
+
 	for post in ${SSG__database}/${posts__dbdir}/hidden_*; do
-		if [ "${post}" = "${SSG__database}/${posts__dbdir}/hidden_*" ]; then
-			echo 'No hidden posts found in database'
+		[ "${post}" = "${SSG__database}/${posts__dbdir}/hidden_*" ] && \
+			echo 'No hidden posts found in database' && \
 			break
-		fi
 
 		if "${posts__parallel_rendering}"; then
-			generateForPost 'hidden' &
-		else
-			generateForPost 'hidden'
+			generate_for_post 'hidden' &
+			continue
 		fi
+
+		generate_for_post 'hidden'
 	done
 
-	unset 'generateForPost'
+	unset 'generate_for_post'
 
 # the files were already copied
 	posts__copy_file()
@@ -142,44 +130,46 @@ __module_name__='posts'
 		posts__generate_list()
 		{
 			local post
-			local currentPageNumber="${1}" # for template
-			local renderedPostDir="${SSG__generated}/${posts__generated_page_directory}${currentPageNumber}" # cache
+			local current_page_number="${1}" # for template
+			local rendered_post_dir="${SSG__generated}/${posts__generated_page_directory}${current_page_number}" # cache
 			local template__html_headers="${posts__list_html_headers}"
 			local template__html_title; posts__list_html_title
 
-			echo "Processing page ${currentPageNumber}"
+			echo "Processing page ${current_page_number}"
 
-			"${posts__no_first_page_mode}" && [ "${currentPageNumber}" = '1' ] && \
-				renderedPostDir="${SSG__generated}/${posts__generated_page_directory}"
+			"${posts__no_first_page_mode}" && [ "${current_page_number}" = '1' ] && \
+				rendered_post_dir="${SSG__generated}/${posts__generated_page_directory}"
 
-			[ ! -e "${renderedPostDir}" ] && mkdir -p "${renderedPostDir}"
+			[ ! -e "${rendered_post_dir}" ] && mkdir -p "${rendered_post_dir}"
 
-			echo -n "${posts__list_header_content}" >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-			templates__current_get_part 'top' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			echo -n "${posts__list_header_content}" >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			templates__current_get_part 'top' >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
 
 			for post in ${2}; do
 				echo " Adding post ${post##*/}"
 
-				local renderedPost="${post##*_}"
-				generatePostBox >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-				unset 'renderedPost'
+				local rendered_post="${post##*_}"
+				generate_post_box >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
+				unset 'rendered_post'
 			done
 
-			if ! templates__current_get_part 'resource' 'posts-pages' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"; then
+			if ! templates__current_get_part 'resource' 'posts-pages' >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"; then
 				echo "error: template ${templates__template} does not provide posts-pages.rc"
 			fi
 
-			templates__current_get_part 'bottom' >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
-			echo -n "${posts__list_footer_content}" >> "${renderedPostDir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			templates__current_get_part 'bottom' >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
+			echo -n "${posts__list_footer_content}" >> "${rendered_post_dir}/${defaults__default_file_name}${defaults__default_file_extension}"
 		}
 
 		# reverse order
-		posts__post_pivot=''
-		for post in ${SSG__database}/${posts__dbdir}/public_*; do
-			posts__post_pivot="${post} ${posts__post_pivot}"
-		done
-		post="${posts__post_pivot}"
-		unset 'posts__post_pivot'
+			posts__post_pivot=''
+
+			for post in ${SSG__database}/${posts__dbdir}/public_*; do
+				posts__post_pivot="${post} ${posts__post_pivot}"
+			done
+
+			post="${posts__post_pivot}"
+			unset 'posts__post_pivot'
 
 		posts__list=''
 		posts__list_limit_indicator='1'
@@ -191,17 +181,22 @@ __module_name__='posts'
 				"${posts__no_first_page_mode}" && posts__no_posts_found_path=''
 
 				mkdir -p "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}"
+
 				echo -n "${posts__not_found_header_content}" >> "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}/${defaults__default_file_name}${defaults__default_file_extension}"
 				templates__current_get_part 'top' >> "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}/${defaults__default_file_name}${defaults__default_file_extension}"
+
 				echo "${posts__label_not_found}" >> "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}/${defaults__default_file_name}${defaults__default_file_extension}"
+
 				templates__current_get_part 'bottom' >> "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}/${defaults__default_file_name}${defaults__default_file_extension}"
 				echo -n "${posts__not_found_footer_content}" >> "${SSG__generated}/${posts__generated_page_directory}${posts__no_posts_found_path}/${defaults__default_file_name}${defaults__default_file_extension}"
 
 				unset 'posts__no_posts_found_path'
+
 				break
 			fi
 
 			posts__list="${posts__list} ${post}"
+
 			if [ "${posts__list_limit_indicator}" = "${posts__posts_per_page}" ]; then
 				if "${posts__parallel_rendering}"; then
 					posts__generate_list "${posts__current_page_indicator}" "${posts__list}" &
@@ -212,10 +207,13 @@ __module_name__='posts'
 				posts__list=''
 				posts__list_limit_indicator='1'
 				posts__current_page_indicator="$((posts__current_page_indicator+1))"
-			else
-				posts__list_limit_indicator="$((posts__list_limit_indicator+1))"
+
+				continue
 			fi
+
+			posts__list_limit_indicator="$((posts__list_limit_indicator+1))"
 		done
+
 		[ ! "${posts__list}" = '' ] && if "${posts__parallel_rendering}"; then
 			posts__generate_list "${posts__current_page_indicator}" "${posts__list}" &
 		else
@@ -243,14 +241,18 @@ __module_name__='posts'
 			cp "${SSG__generated}/${posts__generated_page_directory}1/${defaults__default_file_name}${defaults__default_file_extension}" "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
 		else
 			echo "Generating 'no posts found'"
+
 			echo -n "${posts__not_found_header_content}" >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
 			templates__current_get_part 'top' >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
+
 			echo "${posts__label_not_found}" >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
+
 			templates__current_get_part 'bottom' >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
 			echo -n "${posts__not_found_footer_content}" >> "${SSG__generated}/${defaults__default_file_name}${defaults__default_file_extension}"
 		fi
 	else
-		'Error: posts__enable_post_lists is false - this module cannot be the default module'
+		echo 'Error: posts__enable_post_lists is false - this module cannot be the default module'
+		exit 1
 	fi
 
 exit 0
diff --git a/modules/static/generate b/modules/static/generate
--- a/modules/static/generate
+++ b/modules/static/generate
@@ -1,20 +1,26 @@
 #!/usr/bin/env sh
 # Copy static files to public directory
+[ ! "${@}" = '' ] && exit 1
 __module_name__='static'
 
 static__dbdir='static'
 
 if [ -e "${SSG__database}/${static__dbdir}" ]; then
 		echo 'Copying static files'
+
 		[ ! -e "${SSG__generated}" ] && mkdir -p "${SSG__generated}"
 		cp -rfp ${SSG__database}/${static__dbdir}/* "${SSG__generated}"
+
 		for hiddenfile in ${SSG__database}/${static__dbdir}/.*; do
-			if [ ! "${hiddenfile}" = "${SSG__database}/${static__dbdir}/." ] && [ ! "${hiddenfile}" = "${SSG__database}/${static__dbdir}/.." ]; then
-				cp -rfp "${hiddenfile}" "${SSG__generated}"
+			if [ "${hiddenfile}" = "${SSG__database}/${static__dbdir}/." ] || [ "${hiddenfile}" = "${SSG__database}/${static__dbdir}/.." ]; then
+				continue
 			fi
+
+			cp -rfp "${hiddenfile}" "${SSG__generated}"
 		done
 else
-	echo '"'"${static__dbdir}"'" directory not found in database'
+	echo 'Error: "'"${static__dbdir}"'" directory not found in database'
+	exit 1
 fi
 
 # you can't do that
